### ISSUE TITLE
配置正常，可以接收和回复，但是无法主动推送消息

### ISSUE THREAD

**Issue by poerts** [FlashSoft/node-red-contrib-bizwechat#10]
配置正常，也通过了企业微信后台的接收消息服务器配置的保存，可以正常接收消息和回复，但是主动推送消息始终不行，推送消息的组件在nodered中不报错也没有任何debug输出，是不是企业微信端api调整了？ 还是其他的问题？

已经仔细阅读过完整细节包括提供的nodered的demo代码，都是这种情况

**Comment by poerts** [comment]
sorry消息后来竟然收到了，不过大概有10-20分钟延迟，这个延迟是微信端的问题吗，这么长的延迟好可怕

**Comment by yaming116** [comment]
可能是微信服务器出现问题了，没有做任何延迟或别的处理工作
