### ISSUE TITLE
有无开发计划加入根据post得到的信息推送

### ISSUE THREAD

**Issue by raymond9zhou** [FlashSoft/node-red-contrib-bizwechat#14]
感觉PushBear和Server的最大用途是将设备Post传入的信息推送给关注的用户，本项目中并没有处理Post信息的api可供调用，只能手动推送，对设备信息监控需求而言并无太大作用，想请问有无开发计划在bizwechat.js中加入根据post和get信息将推送给pushbear.js从而进行推送呢？

**Comment by yaming116** [comment]
暂无，开放推送就会涉及安全问题，目前定义了node-red的一个节点。如果你想接入别的，可以在前面添加一个http节点用户第三方程序调用

**Comment by lywly** [comment]
大佬，可以详细说一下怎么实现get请求或post请求推送消息吗。或者如何加http节点就能实现呢？对node-red不熟，现在只知道点击时间戳推送，意义不是很大。

**Comment by xiaoyell** [comment]
> 大佬，可以详细说一下怎么实现get请求或post请求推送消息吗。或者如何加http节点就能实现呢？对node-red不熟，现在只知道点击时间戳推送，意义不是很大。

我也是被这个困住，感觉要学的东西真的太多了……

**Comment by xiaoyell** [comment]
> 大佬，可以详细说一下怎么实现get请求或post请求推送消息吗。或者如何加http节点就能实现呢？对node-red不熟，现在只知道点击时间戳推送，意义不是很大。

https://www.xdawn.cn/index.php/archives/20/
