### ISSUE TITLE
启动命令？

### ISSUE THREAD

**Issue by forthxu** [FlashSoft/node-red-contrib-bizwechat#15]
package里面没有script脚本，写着main:index.js，文件却不存在，怎么启动都没有吧，npm run不支持

**Comment by forthxu** [comment]
https://nodered.org/docs/getting-started/installation

**Comment by yaming116** [comment]
只支持nodered平台

**Comment by forthxu** [comment]
大部分人都不知道node-red是啥东西，我试了半小时都还没搞懂他的流程。

**Comment by yaming116** [comment]
我的意思这个就是为了nodered写的节点，所以....

**Comment by yaming116** [comment]
> 大部分人都不知道node-red是啥东西，我试了半小时都还没搞懂他的流程。

如果你想以别的形式运行，直接把express相关代码抽离出来即可
