### ISSUE TITLE
[端口错误]-Cannot GET /pushbear/2019-11/xxx

### ISSUE THREAD

**Issue by Chernfalin** [FlashSoft/node-red-contrib-bizwechat#20]
点击详情页面，会显示：Cannot GET /pushbear/2019-11/xxx
原因是html url指向了node-red的端口1880，实际应该是3001才对。

为何？如何修复？

**Comment by Chernfalin** [comment]
解决了，发现pushbear url读取的是节点的Url属性，Port属性无效。
Url设置为http://address:3001即可解决。
但是感觉还是一个小bug。

**Comment by yaming116** [comment]
只能说自己好好看看，功能是好的
