### ISSUE TITLE
为什么提示3秒超时应答呢？

### ISSUE THREAD

**Issue by czweb** [FlashSoft/node-red-contrib-bizwechat#22]
调用的是官方的案例，开始是正常的，
![TIM截图20191212162017](https://user-images.githubusercontent.com/5569358/70694976-b5c24c00-1cfb-11ea-9ed3-ecf6fbdbb86a.png)

手机端给在应用内发过一次文字消息后，node-red里就会在下面有个红色的“3秒超时自动应答”，这个是要怎么操作呢？正常吗？
![TIM截图20191212161847](https://user-images.githubusercontent.com/5569358/70694652-1c933580-1cfb-11ea-9a6c-98eddcf5a41d.png)

**Comment by yaming116** [comment]
正常，具体信息看企业微信的文档

**Comment by czweb** [comment]
已经有一个输出为空的信息了，为什么还报错呢？
