### ISSUE TITLE
请问node-red-contrib-bizwechat可否使用HTTPS？

### ISSUE THREAD

**Issue by zslibra** [FlashSoft/node-red-contrib-bizwechat#25]
Nodered 已配置了https，https://xxx.abc.com:1880可以打开nodered页面。

安装了node-red-contrib-bizwechat，按教程操作，bizwechat服务端回调地址新建端口3001， 使用http://xxx.abc.com:3001能正常打开测试页面，但https://xxx.abc.com:3001不能打开。
请问回调地址可否使用HTTPS？
谢谢！

**Comment by GitforZhangXL** [comment]
`const WXBizMsgCrypt = require('wechat-crypto')
const express = require('express')

const WeChat = require('./lib/WeChat')
const Baidu = require('./lib/Baidu')
const { pushBearRouter, indexHtml } = require('./pushbear')
const https = require('https')
const fs = require('fs')

module.exports = RED => {
  // 输入节点
  RED.nodes.registerType('bizwechat-input', class {
    constructor (config) {
      const node = this
      RED.nodes.createNode(node, config)

      const biz_config = RED.nodes.getNode(config.bizwechat)
      // console.log('in biz_config', biz_config)

      const cryptor = new WXBizMsgCrypt(biz_config.token, biz_config.aeskey, biz_config.corpid)
      const wx = new WeChat(node, biz_config, cryptor)
      const bd = new Baidu(node, biz_config)

      const app = express()
      // 证书文件的绝对路径,可以自定义
      const privateKey  = fs.readFileSync('/root/.node-red/cert.key')
      const certificate = fs.readFileSync('/root/.node-red/cert.pem')
      const options = {key: privateKey, cert: certificate}
      const httpsServer = https.createServer(options, app)

      // 接收消息主逻辑
      app.all('/', async (req, res) => {
        if (req.method == 'GET') {
          // === 回调校验用 ==========
          const sVerifyEchoStr = decodeURIComponent(req.query.echostr)
          if (req.query.msg_signature == cryptor.getSignature(req.query.timestamp, req.query.nonce, sVerifyEchoStr)) {
            res.send(cryptor.decrypt(sVerifyEchoStr).message)
          } else {
            res.status(200).send(indexHtml)
          }
        } else {
          // === 正常通讯消息 ==========
          try {
            const message = await wx.getMessage(req)
            console.log(`receive message: ${JSON.stringify(message)}`)
            if (message.MsgType == 'voice' && biz_config.client_id && biz_config.client_id) {
              const amr = await wx.getMedia(message.MediaId)
              const asr = await bd.getAsr(amr)
              message.AsrContent = asr
              console.log(`asr result: ${asr}`)
            }
            node.status({ text: `${message.MsgType}(${message.MsgId})` })
            node.send({ res, req, config: biz_config, message })

            setTimeout(() => {
              node.status({ text: `3秒超时自动应答`, fill: 'red', shape: 'ring' })
              res.end('')
            }, 3000)
          } catch (err) {
            node.status({ text: err.message, fill: 'red', shape: 'ring' })
            node.warn(err)
            res.end('')
          }
        }
      })
      // pushbear逻辑
      app.use('/pushbear', pushBearRouter)

      // 404
      app.use((req, res, next) => {
        res.status(404).end('')
      })
      //配置服务端时填写的回调地址如果以https打头就开启https服务 
      if (biz_config.url.startsWith("https")){
        const server = httpsServer.listen(biz_config.port, () => {
          node.status({ text: `port: ${biz_config.port}`, fill: 'green', shape: 'dot' })
          node.log(`https listening on port ${biz_config.port}`)
        })
      }
      else{
        const server = app.listen(biz_config.port, () => {
          node.status({ text: `port: ${biz_config.port}`, fill: 'green', shape: 'dot' })
          node.log(`listening on port ${biz_config.port}`)
      })}
      server.on('error', ({ message }) => { node.status({ text: message, fill: 'red', shape: 'ring' }) })
      node.on('close', () => server.close())
    }
  })
  // 输出节点
  RED.nodes.registerType('bizwechat-output', class {
    constructor (config) {
      const node = this
      RED.nodes.createNode(node, config)

      const biz_config = RED.nodes.getNode(config.bizwechat)
      // console.log('out biz_config', biz_config)

      node.on('input', data => {
        const { res, message, payload } = data
        const { FromUserName, ToUserName } = message
        const cryptor = new WXBizMsgCrypt(biz_config.token, biz_config.aeskey, biz_config.corpid)
        const wx = new WeChat(node, biz_config, cryptor)
        if (payload) {
          console.log(`revert message: ${payload}`)
          res.end(wx.getSendXML(FromUserName, ToUserName, `${payload}`))
        } else {
          console.log('no revert')
          res.end('')
        }
      })
    }
  })

  // 输出推送
  RED.nodes.registerType('bizwechat-pushbear', class {
    constructor (config) {
      const node = this
      RED.nodes.createNode(node, config)
      const biz_config = RED.nodes.getNode(config.bizwechat)
      node.on('input', async data => {
        try {
          const cryptor = new WXBizMsgCrypt(biz_config.token, biz_config.aeskey, biz_config.corpid)
          const wx = new WeChat(node, biz_config, cryptor)

          // 合并值,未细想
          for (const key in config) { if (config[key] != '' && config[key] != null) { data[key] = config[key] } }
          data.description = data.description || data.payload
          data.touser = data.touser || '@all'
          data.url = data.url || 'https://bbs.iobroker.cn'

          // 发送pushbear类型消息
          await wx.pushbearMessage(data)

          node.status({ text: `发送成功:${data._msgid}` })
          node.send(data)
        } catch (err) {
          node.status({ text: err.message, fill: 'red', shape: 'ring' })
          node.warn(err)
        }
      })
    }
  })

  // 网页内容
  RED.nodes.registerType('bizwechat-template', class {
    constructor (config) {
      const node = this
      RED.nodes.createNode(node, config)
      const biz_config = RED.nodes.getNode(config.bizwechat)
      node.on('input', data => {
        try {
          const cryptor = new WXBizMsgCrypt(biz_config.token, biz_config.aeskey, biz_config.corpid)
          const wx = new WeChat(node, biz_config, cryptor)

          // 合并值,未细想
          for (const key in config) { if (config[key] != '' && config[key] != null) { data[key] = config[key] } }
          data.description = data.description || data.payload

          // 网页内容 存储

          wx.pushbearTemplate(data)

          node.status({ text: `发送成功:${data._msgid}` })
          node.send(data)
        } catch (err) {
          node.status({ text: err.message, fill: 'red', shape: 'ring' })
          node.warn(err)
        }
      })
    }
  })

  // push
  RED.nodes.registerType('bizwechat-push', class {
    constructor (config) {
      const node = this
      RED.nodes.createNode(node, config)

      const biz_config = RED.nodes.getNode(config.bizwechat)
      // console.log('out biz_config', biz_config)

      node.on('input', async data => {
        const { payload } = data
        const cryptor = new WXBizMsgCrypt(biz_config.token, biz_config.aeskey, biz_config.corpid)
        const wx = new WeChat(node, biz_config, cryptor)

        try {
          // 发送用户自定义数据类型消息
          await wx.pushMessage(payload)
          node.status({ text: `发送成功:${data._msgid}` })
          node.send(data)
        } catch (err) {
          node.status({ text: err.message, fill: 'red', shape: 'ring' })
          node.warn(err)
        }
      })
    }
  })

  // upload
  RED.nodes.registerType('bizwechat-upload', class {
    constructor (config) {
      const node = this
      RED.nodes.createNode(node, config)

      const biz_config = RED.nodes.getNode(config.bizwechat)
      // console.log('out biz_config', biz_config)

      node.on('input', async data => {
        const { payload, type, filename } = data
        const cryptor = new WXBizMsgCrypt(biz_config.token, biz_config.aeskey, biz_config.corpid)
        const wx = new WeChat(node, biz_config, cryptor)

        try {
          // 上传临时素材
          const result = await wx.uploadMedia({ file: payload, type, filename })
          node.status({ text: `上传成功:${data._msgid}` })
          data.payload = result
          node.send(data)
        } catch (err) {
          node.status({ text: err.message, fill: 'red', shape: 'ring' })
          node.warn(err)
        }
      })
    }
  })
}
`

以上代码支持https,主要增加
`const https = require('https')
const fs = require('fs')


if (biz_config.url.startsWith("https")){
        const server = httpsServer.listen(biz_config.port, () => {
          node.status({ text: `port: ${biz_config.port}`, fill: 'green', shape: 'dot' })
          node.log(`https listening on port ${biz_config.port}`)
        })
      }
      else{
        const server = app.listen(biz_config.port, () => {
          node.status({ text: `port: ${biz_config.port}`, fill: 'green', shape: 'dot' })
          node.log(`listening on port ${biz_config.port}`)
      })}

`
@yaming116

**Comment by GitforZhangXL** [comment]
全局查找并编辑文件bizwechat.js文件
在第6行的下一行加入以下2行内容，也就是`const { pushBearRouter, indexHtml } = require('./pushbear')`下面
`const https = require('https')`
`const fs = require('fs')`

在第24行的下一行加入以下4行内容，也就是`const app = express()`下面
`const privateKey  = fs.readFileSync('/root/.node-red/cert.key')`
` const certificate = fs.readFileSync('/root/.node-red/cert.pem')`
 `const options = {key: privateKey, cert: certificate}`
` const httpsServer = https.createServer(options, app)`

将下面的内容替换
`const server = app.listen(biz_config.port, () => {`
   `node.status({ text: `port: ${biz_config.port}`, fill: 'green', shape: 'dot' })`
   `node.log(`listening on port ${biz_config.port}`)`
    `})`
为如下：
`if (biz_config.url.startsWith("https")){`
     `const server = httpsServer.listen(biz_config.port, () => {`
     `node.status({ text: `port: ${biz_config.port}`, fill: 'green', shape: 'dot' })`
      `node.log(`https listening on port ${biz_config.port}`)`
      })
}`

`else{`
     `const server = app.listen(biz_config.port, () => {`
     `node.status({ text: `port: ${biz_config.port}`, fill: 'green', shape: 'dot' })`
     `node.log(`listening on port ${biz_config.port}`)`
      `})}`


@FlashSoft 是否考虑在下个版本中加入https支持？

**Comment by yaming116** [comment]
nginx反代即可，没必要程序支持

**Comment by zslibra** [comment]
> 
> 
> 全局查找并编辑文件bizwechat.js文件
> 在第6行的下一行加入以下2行内容，也就是`const { pushBearRouter, indexHtml } = require('./pushbear')`下面
> `const https = require('https')`
> `const fs = require('fs')`
> 
> 在第24行的下一行加入以下4行内容，也就是`const app = express()`下面
> `const privateKey = fs.readFileSync('/root/.node-red/cert.key')`
> ` const certificate = fs.readFileSync('/root/.node-red/cert.pem')`
> `const options = {key: privateKey, cert: certificate}`
> ` const httpsServer = https.createServer(options, app)`
> 
> 将下面的内容替换
> `const server = app.listen(biz_config.port, () => {`
> `node.status({ text: `port: ${biz_config.port}`, fill: 'green', shape: 'dot' })`
> `node.log(`listening on port ${biz_config.port}`)`
> `})`
> 为如下：
> `if (biz_config.url.startsWith("https")){`
> `const server = httpsServer.listen(biz_config.port, () => {`
> `node.status({ text: `port: ${biz_config.port}`, fill: 'green', shape: 'dot' })`
> `node.log(`https listening on port ${biz_config.port}`)`
> })
> }`
> 
> `else{`
> `const server = app.listen(biz_config.port, () => {`
> `node.status({ text: `port: ${biz_config.port}`, fill: 'green', shape: 'dot' })`
> `node.log(`listening on port ${biz_config.port}`)`
> `})}`
> 
> @FlashSoft 是否考虑在下个版本中加入https支持？

清楚明白，成功使用SSL，非常感谢！
也谢谢yaming116开发出这么好用的插件！
