### ISSUE TITLE
node-red-contrib-bizwechat配置好后无法访问

### ISSUE THREAD

**Issue by fkueyu** [FlashSoft/node-red-contrib-bizwechat#33]
Docker的Node-RED版本v2.0.5，node-red-contrib-bizwechat版本v1.1.2
之前配置的节点正常使用，现在想新建一个自己应用把通知分一分，新建了个节点，使用不同的端口号（之前用3001，新建了一个用3002），但始终无法访问（内网都无法访问），端口号也和3001一样从docker中映射出来了。
然后在另一台群晖，新装了Node-RED，安装好node-red-contrib-bizwechat，新建一个节点用3001端口也无法访问。不知道是不是程序的问题，麻烦有空了看一看。

**Comment by yaming116** [comment]
不会有问题的，自己检查端口通不通
