### ISSUE TITLE
几个需要更新的地方

### ISSUE THREAD

**Issue by Lumy88** [FlashSoft/node-red-contrib-bizwechat#4]
1.实际测试，如果语音达到30秒左右，翻译的时间大概率会超过返回信息接收的窗口期，触发重复发送；建议输出端设置一个自动返回空包的选项。
2.百度API在启用后，如果再在conifg里删掉api和secret，ASR服务仍然能调用。

**Comment by yaming116** [comment]
第二个已经修改 #6

**Comment by flashsoft** [comment]
第一个可以直接payload为null就可以，发布版里支持payload为空的时候就返回空包逻辑

**Comment by FlashSoft** [comment]
算了，这个容我加一个30秒尚无返回的自动空包逻辑吧

**Comment by flashsoft** [comment]
经过实际验证，微信为5秒重试机制，先发布一个自动4秒应答空包逻辑，避免微信重试

后续会把现在的应答节点内部机制改为主动发送消息机制，从底层上实现可以应答消息也可以指定消息类型

**Comment by tt508618** [comment]
要怎么推送消息呢？

**Comment by yaming116** [comment]
https://bbs.iobroker.cn/forum.php?mod=viewthread&tid=138&extra=page%3D1&mobile=2 @tt508618

**Comment by tt508618** [comment]
我看了也搭建好了最后还是搞不懂是不是只能点那个时间戳来发送消息？可以像server酱一个api发送的吗？ @yaming116
