### ISSUE TITLE
Error: [微信推送]访问ip不在白名单之中

### ISSUE THREAD

**Issue by leeh11** [FlashSoft/node-red-contrib-bizwechat#42]
首先对作者能提供这么优秀的工具表示感谢！

企业微信『API接收消息』配置通过了，测试推送的时候报白名单错误，如题。我在企业微信后台没有找到相关ip白名单的配置，百度找到一个相似的问题，要在『服务商管理后台』配置，我没有申请服务商啊。。。所以请帮忙分析一下是哪里出的问题。

再次感谢！

**Comment by leeh11** [comment]
我找到配置入口了， 在应用管理里边『企业可信IP』配置，但是我遇到了一个新的问题，我用的是动态ip+阿里ddns, ip会不时变化，有解决办法吗？

**Comment by kingtao1024** [comment]
> 我找到配置入口了， 在应用管理里边『企业可信IP』配置，但是我遇到了一个新的问题，我用的是动态ip+阿里ddns, ip会不时变化，有解决办法吗？

我的IP也是经常变化，每次都需要重新设置，请问有解决办法了吗？
